name: Ship it!

on:
  push:
    branches:
      - trunk

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker tagged metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/extragoodlabs/elixir
          # generate Docker tags based on the following events/attributes
          tags: |
            1.14.5-erlang-25.3.2.3-nojit-alpine-3.18.2
            type=sha
            type=sha,format=long
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
